sysresccd-1.5.2

diff --git a/overlay-squashfs-x86/usr/bin/wizard b/overlay-squashfs-x86/usr/bin/wizard
--- a/overlay-squashfs-x86/usr/bin/wizard
+++ b/overlay-squashfs-x86/usr/bin/wizard
@@ -4,57 +4,19 @@
 DIALOGOPTS='--backtitle SystemRescueCd'
 
 # ------------------------------- checks --------------------------------------
-[ -z "$(which dialog)" ] && exit 0
+[ -z "$(which dialog)" ] && echo "dialog is missing" && exit 1
 
 # ------------------------------- dialog --------------------------------------
-# "Xorg-gen" "Generate a default config for Xorg in /etc/X11/xorg.conf" \
 dialog ${DIALOGOPTS} --title "SystemRescueCd wizard" \
 	--menu "Please select and option and press Enter:" 0 0 0 \
-	"Xorg-run" "Graphical desktop using Xorg (optimal) auto-configuration" \
-	"Xorg-mkx" "Graphical desktop using Xorg (optimal) mkxf86config" \
-	"Xfbdev-run" "Graphical desktop using Xfbdev (alternative)" \
-	"Exit" "Exit this menu and return to shell" 2>/tmp/result
-res=$?
-[ "$res" != '0' ] && exit $res
+	"Xorg-run"   "Graphical desktop using Xorg auto-config (recommended)" \
+	"Xorg-mkx"   "Graphical desktop using Xorg mkxf86config (alternative)" \
+	"Xfbdev-run" "Graphical desktop using Xfbdev (requires Frame-Buffer)" \
+	"Xorg-gen"   "Generate /etc/X11/xorg.conf that can be edited manually" \
+	"Exit"       "Exit this menu and return to shell" 2>/tmp/result || exit 1
 
 choice="$(cat /tmp/result)"
 rm -f /tmp/result
-
-xfbdev_cfg()
-{
-	dialog	${DIALOGOPTS} --title "Xfbdev configuration" \
-		--menu "Select your screen configuration:" 0 0 0 \
-		"640x480x8"    "640x480   (8bits -  256 colors)" \
-		"640x480x24"   "640x480   (24bits - 16.7 millions colors)" \
-		"800x600x8"    "800x600   (8bits -  256 colors)" \
-		"800x600x24"   "800x600   (24bits - 16.7 millions colors)" \
-		"1024x768x8"   "1024x768  (8bits -  256 colors)" \
-		"1024x768x24"  "1024x768  (24bits - 16.7 millions colors)" \
-		"1280x1024x8"  "1280x1024 (8bits -  256 colors)" \
-		"1280x1024x24" "1280x1024 (24bits - 16.7 millions colors)" \
-		"1600x1200x8"  "1600x1200 (8bits -  256 colors)" \
-		"1600x1200x24" "1600x1200 (24bits - 16.7 millions colors)" 2>/tmp/result
-	if [ "$?" = '0' ]
-	then
-		choice="$(cat /tmp/result)"
-		echo "forcevesa=${choice}" > /root/xserver.cfg
-		return 0
-	else
-		echo "" > /root/xserver.cfg
-		return 1
-	fi
-}
-
-error_amd64()
-{
-	msg=''
-	msg="${msg}Sorry, Xfbdev does not work with 64bits\n"
-	msg="${msg}kernels (rescue64 and altker64).\n"
-	msg="${msg}You have to start SystemRescueCd using \n"
-	msg="${msg}either the rescuecd or the altker32 kernel.\n"
-	msg="${msg}You can also use Xorg that works on amd64.\n"
-	dialog --title "Error" --msgbox "${msg}" 10 55
-}
 
 # ------------------------------- functions ------------------------------------
 case "$choice" in
@@ -64,22 +26,24 @@ case "$choice" in
 		;;
 	Xorg-mkx)
 		echo "forcexorg" > /root/xserver.cfg
+		/usr/sbin/hwsetup
 		/usr/sbin/mkxf86config.sh
 		startx
 		;;
 	Xfbdev-run)
-		#if [ "$(uname -m)" = "x86_64" ]
-		#then
-		#	error_amd64 && exec "$0"
-		#else
+		if [ ! -c /dev/fb0 ]
+		then
+			dialog --title "Error" --msgbox "You have to start in framebuffer (high resolution) mode to use Xfbdev." 10 75
+			exit 1
+		fi
 		echo "forcevesa" > /root/xserver.cfg
 		startx
-		#fi
 		;;
 	Xorg-gen)
-		Xorg -configure >/dev/null 2>&1
 		[ -f /etc/X11/xorg.conf ] && mv /etc/X11/xorg.conf /etc/X11/xorg.old
+		Xorg -configure >/dev/null 2>&1
 		mv /root/xorg.conf.new /etc/X11/xorg.conf
+		dialog --title "Information" --msgbox "The XOrg configuration file has been generated in /etc/X11/xorg.conf" 10 75
 		;;
 	Exit)
 		exit 0
diff --git a/portage-overlay/dev-util/catalyst/files/catalyst-2.0.6-sysresccd.patch b/portage-overlay/dev-util/catalyst/files/catalyst-2.0.6-sysresccd.patch
--- a/portage-overlay/dev-util/catalyst/files/catalyst-2.0.6-sysresccd.patch
+++ b/portage-overlay/dev-util/catalyst/files/catalyst-2.0.6-sysresccd.patch
@@ -1,6 +1,6 @@
 diff -urN catalyst-2.0.6-a/modules/generic_stage_target.py catalyst-2.0.6-b/modules/generic_stage_target.py
 --- catalyst-2.0.6-a/modules/generic_stage_target.py	2008-05-29 05:30:10.000000000 +0100
-+++ catalyst-2.0.6-b/modules/generic_stage_target.py	2009-11-01 10:42:17.000000000 +0000
++++ catalyst-2.0.6-b/modules/generic_stage_target.py	2010-04-03 15:46:58.000000000 +0100
 @@ -426,7 +426,7 @@
  
  	def set_snapshot_path(self):
@@ -10,15 +10,15 @@ diff -urN catalyst-2.0.6-a/modules/generic_stage_target.py catalyst-2.0.6-b/modu
  
  		if os.path.exists(self.settings["snapshot_path"]):
  			self.settings["snapshot_path_hash"]=\
-@@ -684,7 +684,7 @@
- 					self.settings["source_path"]+"\nto "+\
- 					self.settings["chroot_path"]+\
- 						" (This may take some time) ...\n"
--				unpack_cmd="tar xjpf "+self.settings["source_path"]+" -C "+\
-+				unpack_cmd="tar xpf "+self.settings["source_path"]+" --lzma -C "+\
- 					self.settings["chroot_path"]
- 				error_msg="Tarball extraction of "+\
- 					self.settings["source_path"]+" to "+\
+@@ -809,7 +809,7 @@
+ 			cleanup_errmsg="Error removing existing snapshot directory."
+ 			cleanup_msg=\
+ 				"Cleaning up existing portage tree (This can take a long time)..."
+-			unpack_cmd="tar xjpf "+self.settings["snapshot_path"]+" -C "+\
++			unpack_cmd="tar xpf "+self.settings["snapshot_path"]+" --lzma -C "+\
+ 				self.settings["chroot_path"]+"/usr"
+ 			unpack_errmsg="Error unpacking snapshot"
+ 
 @@ -1055,6 +1055,13 @@
  			else:
  				myf.write('CXXFLAGS="${CFLAGS}"\n')
@@ -35,7 +35,7 @@ diff -urN catalyst-2.0.6-a/modules/generic_stage_target.py catalyst-2.0.6-b/modu
  				myf.write('LDFLAGS="'+self.settings["LDFLAGS"]+'"\n')
 diff -urN catalyst-2.0.6-a/modules/snapshot_target.py catalyst-2.0.6-b/modules/snapshot_target.py
 --- catalyst-2.0.6-a/modules/snapshot_target.py	2008-05-29 05:30:11.000000000 +0100
-+++ catalyst-2.0.6-b/modules/snapshot_target.py	2009-11-01 10:42:17.000000000 +0000
++++ catalyst-2.0.6-b/modules/snapshot_target.py	2010-04-03 15:46:58.000000000 +0100
 @@ -17,7 +17,7 @@
  		self.settings["target_subpath"]="portage"
  		st=self.settings["storedir"]
@@ -47,30 +47,43 @@ diff -urN catalyst-2.0.6-a/modules/snapshot_target.py catalyst-2.0.6-b/modules/s
  			print "\nWarning!!!!"
 diff -urN catalyst-2.0.6-a/targets/support/chroot-functions.sh catalyst-2.0.6-b/targets/support/chroot-functions.sh
 --- catalyst-2.0.6-a/targets/support/chroot-functions.sh	2008-05-29 05:30:09.000000000 +0100
-+++ catalyst-2.0.6-b/targets/support/chroot-functions.sh	2009-11-01 10:42:17.000000000 +0000
-@@ -126,6 +126,7 @@
++++ catalyst-2.0.6-b/targets/support/chroot-functions.sh	2010-04-03 15:46:58.000000000 +0100
+@@ -126,6 +126,9 @@
  	else
  		clst_myemergeopts="--quiet"
  	fi
-+	clst_myemergeopts="${clst_myemergeopts} --jobs=4 --load-average=8"
++	# set "--keep-going" to bypass compilation errors and continue
++	clst_myemergeopts="${clst_myemergeopts} -u" # required with >=portage-2.1.7
++	clst_myemergeopts="${clst_myemergeopts} --jobs=1 --load-average=8" # workaround parallel build issues in stage1
  	if [ -n "${clst_FETCH}" ]
  	then
  		export bootstrap_opts="-f"
+diff -urN catalyst-2.0.6-a/targets/support/filesystem-functions.sh catalyst-2.0.6-b/targets/support/filesystem-functions.sh
+--- catalyst-2.0.6-a/targets/support/filesystem-functions.sh	2008-05-29 05:30:09.000000000 +0100
++++ catalyst-2.0.6-b/targets/support/filesystem-functions.sh	2010-04-03 15:48:05.000000000 +0100
+@@ -53,6 +53,7 @@
+ create_squashfs() {
+ 	echo "Creating squashfs..."
+ 	export loopname="image.squashfs"
++	find ${clst_destpath} -type f -name "*.py?" -exec rm -f {} \;
+ 	mksquashfs "${clst_destpath}" "$1/${loopname}" ${clst_fsops} -noappend \
+ 		|| die "mksquashfs failed, did you emerge squashfs-tools?"
+ }
 diff -urN catalyst-2.0.6-a/targets/support/kmerge.sh catalyst-2.0.6-b/targets/support/kmerge.sh
 --- catalyst-2.0.6-a/targets/support/kmerge.sh	2008-05-29 05:30:09.000000000 +0100
-+++ catalyst-2.0.6-b/targets/support/kmerge.sh	2009-11-01 10:42:17.000000000 +0000
++++ catalyst-2.0.6-b/targets/support/kmerge.sh	2010-04-03 15:46:58.000000000 +0100
 @@ -99,7 +99,7 @@
  	fi
  	if [ "${clst_kernel_merge}" != "" ]
  	then
 -		genkernel --callback="emerge ${gk_callback_opts} ${clst_kernel_merge}" \
-+		genkernel --callback="emerge --jobs=4 --load-average=8 ${gk_callback_opts} ${clst_kernel_merge}" \
++		genkernel --callback="emerge -u --jobs=4 --load-average=8 --accept-properties=-interactive ${gk_callback_opts} ${clst_kernel_merge}" \
  			${GK_ARGS} || exit 1
  	else
  		genkernel ${GK_ARGS} || exit 1
 diff -urN catalyst-2.0.6-a/targets/support/unmerge.sh catalyst-2.0.6-b/targets/support/unmerge.sh
 --- catalyst-2.0.6-a/targets/support/unmerge.sh	2008-05-29 05:30:09.000000000 +0100
-+++ catalyst-2.0.6-b/targets/support/unmerge.sh	2009-11-01 12:11:47.000000000 +0000
++++ catalyst-2.0.6-b/targets/support/unmerge.sh	2010-04-03 15:46:58.000000000 +0100
 @@ -2,6 +2,77 @@
  
  source /tmp/chroot-functions.sh
diff --git a/portage-overlay/sys-apps/sysresccd-scripts/files/sysresccd-pkgstats b/portage-overlay/sys-apps/sysresccd-scripts/files/sysresccd-pkgstats
--- a/portage-overlay/sys-apps/sysresccd-scripts/files/sysresccd-pkgstats
+++ b/portage-overlay/sys-apps/sysresccd-scripts/files/sysresccd-pkgstats
@@ -1,5 +1,4 @@
 #!/bin/bash
-# /usr/lib/catalyst/targets/support/unmerge.sh
 # Distributed under the terms of the GNU General Public License v2
 
 DO_EIX=1
@@ -14,20 +13,23 @@ FILEPATH_LST='/root/sysresccd-lst.txt'
 # =========================================================================
 # ======================= create the package list =========================
 # =========================================================================
-equery -q -C list -i | grep -v '^virtual' >|  ${FILEPATH_PKG}
+if [ -n "$(which equery)" ]
+then
+	equery -q -C list -i | grep -v '^virtual' >|  ${FILEPATH_PKG}
+fi
 
 # -------------------------------------------------------------------------
-if [ -n "(which eix)" ] && [ "${DO_EIX}" = '1' ]
+if [ -n "$(which eix)" ] && [ "${DO_EIX}" = '1' ]
 then
 	echo "---> generating ${FILEPATH_EIX}"
-	update-eix
+	/usr/bin/eix-update || echo "eix-update failed"
 	FORMAT='<category>/<name>-<installedversions>' eix -I -n | grep -v '^virtual' | \
 		sed -r -e 's|[0-9]{2}:[0-9]{2}:[0-9]{2} [AMP ]*[0-9]{2}/[0-9]{2}/[0-9]{0,4}| : |g' -e 's| : $||g' -e 's|^\t{2,}|  |g' | \
 		grep '^[a-z0-9]*-[a-z0-9]*/[a-z0-9]*' | sed -e 's!\[?\]!!g' > ${FILEPATH_EIX}
 fi
 
 # -------------------------------------------------------------------------
-if [ -n "(which equery)" ] && [ "${DO_LST}" = '1' ]
+if [ -n "$(which equery)" ] && [ "${DO_LST}" = '1' ]
 then
 	echo "---> generating ${FILEPATH_LST}"
 	for curpkg in $(cat ${FILEPATH_PKG})
@@ -36,13 +38,13 @@ then
 		sizraw=$(equery -q -C size -b -e ${curpkg} | xargs | sed -r -e 's!.*size\(([0-9]*)\).*!\1!g')
 		sizfmt=$(printf "%d kb" $((sizraw/1024)))
 		echo '' >> "${FILEPATH_LST}"
-		echo "=========================${curpkg} (size=${sizfmt})========================" >> "${FILEPATH_LST}"
+		echo "=======================${curpkg} (size=${sizfmt})======================" >> "${FILEPATH_LST}"
 		equery -C files "=${curpkg}" 2>/dev/null | grep '^/' >> "${FILEPATH_LST}"
 	done
 fi
 
 # -------------------------------------------------------------------------
-if [ -n "(which equery)" ] && [ "${DO_SIZ}" = '1' ]
+if [ -n "$(which equery)" ] && [ "${DO_SIZ}" = '1' ]
 then
 	echo "---> generating ${FILEPATH_SIZ}"
 	for curpkg in $(cat ${FILEPATH_PKG})
@@ -58,3 +60,4 @@ then
 		echo ${output}
 	done
 fi
+
